extends: default

rules:
  line-length:
    max: 120
    level: warning

  indentation:
    spaces: 2

  trailing-spaces:
    level: warning

  comments:
    min-spaces-from-content: 1

  new-lines:
    type: unix

exclude:
  - .github/
