# ── OVERVIEW ────────────────────────────────────────────────────────────────
- title: "Stack – Overview"
  difficulty: "easy"
  tags: ["stack", "identify"]
  Front: |
    Which data structure …

    - Operates on a **last-in, first-out** principle
    - Supports **push** and **pop** in **O(1)**
    - Is used for recursion call stacks and undo features
  Back: "Stack"

# ── OPERATION CARDS ─────────────────────────────────────────────────────────
- title: "Stack – Search"
  difficulty: "easy"
  tags: ["stack", "search"]
  Front: |
    What data structure operation does this implement? What is its time complexity?

    ```go
    found := false
    target := 5
    for _, v := range stack {
        if v == target { found = true; break }
    }
    ```
  Back: |
    Linear search (O(n))

    Stacks are not designed for search — you must iterate through all elements. If you frequently need lookup, consider a hash set alongside the stack.
