# ── OVERVIEW ────────────────────────────────────────────────────────────────
- title: "Stack – Overview"
  difficulty: "easy"
  tags: ["stack", "identify"]
  Front: |
    Which data structure …

    - Operates on a **last-in, first-out** principle
    - Supports **push** and **pop** in **O(1)**
    - Is used for recursion call stacks and undo features
  Back: "Stack"
